### ISSUE TITLE
大佬，这个用python什么版本呀，centos依赖安不上，windows启动不了。。。

### ISSUE THREAD

**Issue by jason1235** [mzdluo123/SanforProxy#1]
C:\SanforProxy>mitmweb -k -s main.py
Traceback (most recent call last):
  File "c:\program files\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\python\Scripts\mitmweb.exe\__main__.py", line 5, in <mo
dule>
  File "c:\program files\python\lib\site-packages\mitmproxy\__init__.py", line 9
, in <module>
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
AttributeError: module 'asyncio' has no attribute 'WindowsSelectorEventLoopPolic
y'

**Comment by mzdluo123** [comment]
可能是Python版本问题，请使用3.7及以上版本
